package com.mycompany.mandelbrot;

/**
 *
 * @author Cory
 */
public class Options extends javax.swing.JPanel
{

    /**
     * Creates new form Options
     */
    public Options()
    {
        initComponents();
        InputOptions defaultOptions = new InputOptions();
        this.xcData.setText(String.valueOf(defaultOptions.getXc()));
        this.ycData.setText(String.valueOf(defaultOptions.getYc()));
        this.sizeData.setText(String.valueOf(defaultOptions.getSize()));
        this.NData.setText(String.valueOf(defaultOptions.getN()));
        this.maxData.setText(String.valueOf(defaultOptions.getMax()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        xc = new javax.swing.JLabel();
        xcData = new javax.swing.JTextField();
        yc = new javax.swing.JLabel();
        ycData = new javax.swing.JTextField();
        size = new javax.swing.JLabel();
        sizeData = new javax.swing.JTextField();
        N = new javax.swing.JLabel();
        NData = new javax.swing.JTextField();
        max = new javax.swing.JLabel();
        maxData = new javax.swing.JTextField();

        xc.setText("Xc");

        xcData.setText("jTextField1");

        yc.setText("Yc");

        ycData.setText("jTextField1");

        size.setText("size");

        sizeData.setText("jTextField1");

        N.setText("N");

        NData.setText("jTextField1");

        max.setText("max");

        maxData.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(size)
                        .addGap(18, 18, 18)
                        .addComponent(sizeData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(yc)
                            .addGap(18, 18, 18)
                            .addComponent(ycData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(max)
                            .addGap(18, 18, 18)
                            .addComponent(maxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(xc)
                            .addGap(18, 18, 18)
                            .addComponent(xcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(N)
                            .addGap(18, 18, 18)
                            .addComponent(NData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xc)
                    .addComponent(xcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(N)
                        .addComponent(NData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yc)
                    .addComponent(ycData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(max)
                        .addComponent(maxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(size)
                    .addComponent(sizeData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel N;
    private javax.swing.JTextField NData;
    private javax.swing.JLabel max;
    private javax.swing.JTextField maxData;
    private javax.swing.JLabel size;
    private javax.swing.JTextField sizeData;
    private javax.swing.JLabel xc;
    private javax.swing.JTextField xcData;
    private javax.swing.JLabel yc;
    private javax.swing.JTextField ycData;
    // End of variables declaration//GEN-END:variables

    public InputOptions getInputOptions()
    {
        return new InputOptions(getXcData(), getYcData(), getSizeData(), getNData(), getMaxData());
    }

    private double getXcData()
    {
        return Double.parseDouble(xcData.getText());
    }

    private double getYcData()
    {
        return Double.parseDouble(ycData.getText());
    }

    private double getSizeData()
    {
        return Double.parseDouble(sizeData.getText());
    }

    private int getNData()
    {
        return Integer.parseInt(NData.getText());
    }

    private int getMaxData()
    {
        return Integer.parseInt(maxData.getText());
    }

}
